### PR TITLE
Create SAML iOS swift app

### PR DESCRIPTION
**Pull request by danielpassos**
See: [FH-2535](https://issues.jboss.org/browse/FH-2535)

### CODE REVIEW

**Comment by danielpassos** [comment]
@corinnekrych Could review that?

PS: I'm using [fixed UUID](https://github.com/danielpassos/saml-ios-swift/blob/master/saml-ios-swift/HomeViewController.swift#L19) because [SDK are creating a new one every time](https://github.com/feedhenry/fh-ios-swift-sdk/blob/master/FeedHenry/Config/Config.swift#L80)

**Comment by corinnekrych** [comment]
@danielpassos here is some comments: https://github.com/danielpassos/saml-ios-swift/pull/1
I'll fix the UUID, nice catch, it was left as todo.

**Comment by danielpassos** [comment]
@corinnekrych Updated. Could you do a double check before I merge?

**Comment by corinnekrych** [comment]
@danielpassos last polishing: add headers/license/README file and we're good to

**Comment by danielpassos** [comment]
@corinnekrych Done!

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
